# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'FISCardStreams' do
	pod "AFNetworking", "~> 2.0"
	pod 'AFOAuth2Manager'
	pod 'MONActivityIndicatorView'
	pod 'NSURL+QueryDictionary'
	pod 'RGCardViewLayout','1.0'
	pod 'UIColor+uiGradients'
	pod 'Hex'

end

target 'FISCardStreamsTests' do
	pod 'Specta'
	pod 'Expecta'
	pod 'OCMock'

end

