# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'FISCardStreams' do
	pod "AFNetworking", "~> 2.0"
	pod 'AFOAuth2Manager'
	pod 'MONActivityIndicatorView'
	pod 'NSURL+QueryDictionary'

end

target 'FISCardStreamsTests' do

end

